---
Name: dropdown2autocomplete
Before: 'app/*'
After: 'framework/*','cms/*'
---

Dropdown2AutocompleteField:
 js_settings: '{search_contains: true, allow_single_deselect: true}'
 
GroupedDropdown2AutocompleteField:
 js_settings: '{search_contains: true, allow_single_deselect: true}'

GroupedDropdown2AutocompleteField:
 js_settings: '{search_contains: true, allow_single_deselect: true}'
